### PR TITLE
Feature/record cli

### PR DESCRIPTION
**Pull request by MilkClouds**
I added CLI executable to record given window name or monitor index. This CLI executable will work as example of this library's application.

Features
- get window_name or monitor_index
- get cursor_capture and draw_border
- get path
- show up FPS of capture(which is NOT recorded video files fps)
- graceful exit with ctrl+c
- automatically detect window / monitor 's height/width and save into video file

Some minor concerns
- Is it okay to maintain the CLI's Cargo dependencies together with the main project's dependencies?

### CODE REVIEW

**Comment by MilkClouds** [comment]
And I'm thinking about adding logic to automatically set the width, height, and therefore the bitrate adaptively.

**Comment by raags** [comment]
Actually I just realised triggering [GraphicsCapturePicker](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturepicker?view=winrt-26100) is all that's needed

**Comment by NiiightmareXD** [comment]
Hey, I don't know how did I missed this PR I review it when I got home, thanks.

**Comment by NiiightmareXD** [comment]
Looks good, thanks.

**Comment by raags** [comment]
@NiiightmareXD thanks for merging, any plans to implement [GraphicsCapturePicker](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturepicker?view=winrt-26100)?

**Comment by NiiightmareXD** [comment]
> @NiiightmareXD thanks for merging, any plans to implement [GraphicsCapturePicker](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturepicker?view=winrt-26100)?

Yes, but implementing that in win32 apps is somewhat weird and you need to have an active window, which I don't know what is the way to do that.

**Pull request merged**
